version: "3.8"

services:
  db:
    container_name: coder_db
    image: postgres
    ports:
      - 54325:5432
    env_file:
      - ./api/.env
    environment:
      - POSTGREST_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - TZ=Asia/Seoul
    networks:
      - hello_network

  api:
    build: .
    container_name: coder_api
    ports:
      - 8800:80
      - 587:587
    volumes:
      - ./api:/api
    env_file:
      - ./api/.env
    command: >
      bash -c "
      uvicorn api.main:app --reload-dir ./api --host 0.0.0.0 --port 80 --debug "

    #command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--debug", "--port", "80", "--reload-dir", "./api"]
    networks:
      - hello_network
    depends_on:
      - db

networks:
  hello_network:
    driver: bridge
